
# - warn: {lhs: "(?) x y", rhs: "x ? y", name: Use infix, side: isInfixApp original}
# - warn: {lhs: "(?) x y", rhs: "x ? y", name: Use infix, side: isVar original}
# - warn: {lhs: "(?) x y", rhs: "x ? y", name: Use infix, side: isApp original}
- warn: {lhs: "(?) x y", rhs: "x ? y", name: Use infix, side: isTmp original}
